version: '3'

services:
  app:
    build: ./dockerfiles/node
    links:
      - dynamodb
      - mysql
      - redis
    ports:
      - '3000:3000'
      - '9229:9229'
    tty: true
    container_name: node_app

  dynamodb:
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./db_data/dynamo:/home/dynamodblocal/data/
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    container_name: dynamodb

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    volumes:
      - ./db_data/mysql:/var/lib/mysql
    container_name: mysql

  redis:
    build: ./dockerfiles/redis
    restart: always
    ports:
      - '6739:6739'
    volumes:
      - ./db_data/redis:/data
    container_name: redis
