version: '3'

services:
  app:
    build: ./dockerfiles/node
    links:
      - dynamodb
      - redis
    ports:
      - '3000:3000'
      - '9229:9229'
    container_name: node_app
    tty: true

  dynamodb:
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./db_data/dynamo:/home/dynamodblocal/data/
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data

  redis:
    build: ./dockerfiles/redis
    restart: always
    ports:
      - '6739:6739'
    volumes:
      - ./db_data/redis:/data
